image: node:12.5.0

cache:
  paths:
    - node_modules/

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build-storybook -- -o public
  artifacts:
    paths:
      - public
  only:
    - master
